  [build]
  base    = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[[redirects]]
  # This rule now forwards the /api part as well.
  from = "/api/*"
  to = "https://shiksha-sahayak-backend.onrender.com/:splat" 
  status = 200